name: 'AI Patch Doctor'
description: 'Zero-config CI check for AI API issues: 429s, retries, streaming, timeouts, cost. No API keys needed.'
author: 'Michael Brinkworth'

branding:
  icon: 'activity'
  color: 'blue'

inputs:
  telemetry:
    description: 'Enable telemetry (disabled by default for privacy)'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Cache npm
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-ai-doctor
        restore-keys: |
          ${{ runner.os }}-npm-
    
    - name: Run AI Patch Doctor
      shell: bash
      run: |
        if [ "${{ inputs.telemetry }}" = "true" ]; then
          npx -y ai-patch doctor --fix
        else
          npx -y ai-patch doctor --fix --no-telemetry
        fi
    
    - name: Display Report
      shell: bash
      run: |
        if [ -f "report.md" ]; then
          echo "## AI Patch Doctor Report"
          cat report.md
        else
          echo "No report generated (scanning may have failed or no issues found)"
        fi
